development:
  adapter: postgresql
  encoding: unicode
  database: mentu
  host: localhost
  username: postgres
  password: password
test:
  adapter: postgresql
  encoding: unicode
  database: mentu_test
  host: localhost
  pool: 5
  username: postgres
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: mentu_production
  pool: 25
  username: root
  password: password