development:
  adapter: postgresql
  encoding: unicode
  database: mentu
  host: localhost
  username: mentu
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: mentu_test
  host: localhost
  pool: 5
  username: mentu
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: mentu_production
  pool: 25
  username: mentu
  password: